---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-catalogserver
  namespace: openshift-catalogd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    control-plane: controller-manager
